server:
  port: 9001
  servlet:
    context-path: /demo
spring:
  application:
    name: nacos-provider
  cloud:
    discovery:
#      server-addr: 127.0.0.1:8848
      server-addr: http://192.168.93.124:81

management:
  endpoint:
    web:
      exposure:
        include:'*'