server:
  port: 9999
spring:
  application:
    name: cloud-gateway-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    gateway:
      discovery:
        locator:
          enabled: true #开启注册中心路由功能
      routes: # 路由
        - id: nacos-provider #路由ID，没有固定要求，但是要保证唯一，建议配合服务名
          uri: lb://nacos-provider # 匹配提供服务的路由地址
          predicates: # 断言
            - Path=/msb/** # 断言，路径相匹配进行路由
#            - After=2022-11-14T20:50:38.636+08:00[Asia/Shanghai]
#            - Cookie=username,[a-z]+ # 匹配Cookie的key和value（正则表达式）
#            - Header=X-Request-Id,\d+ #表示数字
#          filters:
#            - StripPrefix=1 # 去掉地址中的第一部分

management:
  endpoints:
    web:
      exposure:
        include: '*'